name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/job-runner

jobs:
  Infra-Setup:
    if: contains(join(github.event.commits.*.modified, ','), 'infra/main.tf')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra
  Build-and-Push:
    needs: Infra-Setup
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
  Update-Image-Tag-ArgoCD:
    needs: Build-and-Push
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Update GitOps repo
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/tejas261/go-job-runner-gitops.git
          cd go-job-runner-gitops
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' job-runner-chart/values.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add job-runner-chart/values.yaml
          git commit -m "update image tag to ${{ github.sha }}"
          git push